package com.myfirstproject.day06;

import com.myfirstproject.utilities.TestBase;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.By;

public class Day06_Alerts extends TestBase {
    /*
        What is alert?
        -it is a pop up that is generated by JS
        -alerts are used to give informational messages
        -when there is an alert pop up on the page, we must handle the alert otherwise we cannot move on
        How do you handle alerts?
        -switch to alert then use
        accept to click OK,
        dismiss to click Cancel,
        getText to get the text,
        and sendKeys to type on the alert
         */
    @Test
    public void acceptAlert(){
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        //        click on the first alert
        driver.findElement(By.xpath("//button[@onclick='jsAlert()']")).click();
        //       verify the text “I am a JS Alert”
        String actualJsAlert = driver.switchTo().alert().getText();
        String expectedJsAlert ="I am a JS Alert";
        Assert.assertEquals(expectedJsAlert,actualJsAlert);
        //       click OK
        driver.switchTo().alert().accept();
        String actualResultText01 =driver.findElement(By.xpath("//p[@id='result']")).getText();
        String expectedResultText01 = "You successfully clicked an alert";
        Assert.assertEquals(expectedResultText01,actualResultText01);

    }
    @Test
    public void dismissAlert(){
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        //  click on the second alert
        driver.findElement(By.xpath("//button[@onclick='jsConfirm()']")).click();
        //  verify text "I am a JS Confirm”
        String actualJsConfirmText = driver.switchTo().alert().getText();
        String expectedJsConfirmText = "I am a JS Confirm";
        Assert.assertEquals(expectedJsConfirmText,actualJsConfirmText);
        //  click cancel
        driver.switchTo().alert().dismiss();
        //  Verify “You clicked: Cancel”
        String actualResulText02 = driver.findElement(By.xpath("//p[@id='result']")).getText();
        String expectedResulText02 = "You clicked: Cancel";
        Assert.assertEquals(expectedResulText02,actualResulText02);
    }
    @Test
    public void sendKeysAlert(){
    /*
    sendKeysAlert()=> click on the third alert,
    verify text “I am a JS prompt”,
    type “Hello World”,
    click OK,
    and Verify “You entered: Hello World”
    Collapse
     */
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
//        click on the third alert
        driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();
//        verify text “I am a JS prompt”
        String actualAlertText = driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS prompt",actualAlertText);
//       type “Hello World”
        driver.switchTo().alert().sendKeys("Hello World");
//        click OK
        driver.switchTo().alert().accept();
//        and Verify “You entered: Hello World”
        String actualResultText = driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You entered: Hello World",actualResultText);
    }
}
